name: Build (Zephyr)

on: [push, pull_request]

jobs:
  build:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    container:
      image: zephyrprojectrtos/ci:latest
    env:
      THRIFT_VERSION: 0.16.0
      CMAKE_PREFIX_PATH: /opt/toolchains
      # To prevent apt from prompting the user to enter locale info
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: thrift-for-zephyr

      - name: Update APT package database
        working-directory: /
        run: |
          apt-get update

      - name: Install Thrift
        working-directory: /
        run: |
          apt install -y libboost-all-dev thrift-compiler libthrift-dev

      - name: Initialize Project with West
        working-directory: thrift-for-zephyr
        run: |
          pip3 install -U west
          west init -l .
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt

      - name: Build and Run Testsuite
        working-directory: thrift-for-zephyr
        run: |
          source zephyr-env.sh
          twister -i -G -T tests/

      - name: Build Samples
        working-directory: thrift-for-zephyr
        run: |
          source zephyr-env.sh
          twister -i --build-only -G -T samples/
