name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      THRIFT_VERSION: 0.16.0
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: thrift-for-zephyr

      - name: Initialize
        working-directory: thrift-for-zephyr
        run: |
          echo "PATH=$PWD/../zephyr/scripts:$PATH" >> $GITHUB_ENV
          wget https://github.com/cfriedt/thrift-debs/releases/download/v${THRIFT_VERSION}/libthriftc_${THRIFT_VERSION}-1.x86_64.deb
          wget https://github.com/cfriedt/thrift-debs/releases/download/v${THRIFT_VERSION}/libthrift_${THRIFT_VERSION}-1.x86_64.deb
          wget https://github.com/cfriedt/thrift-debs/releases/download/v${THRIFT_VERSION}/thrift_${THRIFT_VERSION}-1.x86_64.deb
          dpkg -i libthriftc_${THRIFT_VERSION}-1.x86_64.deb
          dpkg -i libthrift_${THRIFT_VERSION}-1.x86_64.deb
          dpkg -i thrift_${THRIFT_VERSION}-1.x86_64.deb
          pip3 install -U west
          west init -l .
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt

      - name: Build and run Testsuite
        working-directory: thrift-for-zephyr
        run: |
          twister -i -p qemu_x86_64 -T tests/lib/thrift/hello

      - name: Build Samples
        working-directory: thrift-for-zephyr
        run: |
          twister -b -p qemu_x86_64 -T samples/lib/thrift/hello_server

#      - name: Archive firmware
#        uses: actions/upload-artifact@v2
#        with:
#          name: firmware
#          path: thrift-for-zephyr/build/zephyr/zephyr.*
