name: Build (Zephyr)

on:
  push:
    branches:
      - main
      - v*-branch
  pull_request:
    branches:
      - main
      - v*-branch
  schedule:
    # Run at 00:42 on Thursday and Tuesday
    - cron: '42 0 * * 4,2'

jobs:
  build:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    container:
      image: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
      # To prevent apt from prompting the user to enter locale info
      DEBIAN_FRONTEND: noninteractive
      # Update west modules minimally for CI
      # Note the --group-filter argument is still not really useful because
      # - it pulls in way too much by default
      #   - many modules do not belong to a group
      #   - the default is to include all modules
      # - it is impossible to start a group filter with a dash e.g. -debug
      # For reference: west update --group-filter +crypto,-debug,-fs,-hal,-tee,-tools
      WEST_MODULES: cmsis mbedtls
    steps:
      - name: Update APT package database
        working-directory: /
        run: |
          apt-get update

      - name: Install Thrift
        working-directory: /
        run: |
          apt install -y libboost-all-dev thrift-compiler libthrift-dev

      - name: Initialize Project with West
        run: |
          pip3 install -U west
          west init zephyrproject
          cd zephyrproject
          west update $WEST_MODULES

      - name: Checkout Thrift Module
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: zephyrproject/modules/lib/thrift

      - name: Add Thrift Submanifest
        # Note: this is manually cloned above, but the submanifest
        # must be there for west to automatically include the module.
        # Users should use cat << EOF here as shown in README.md.
        working-directory: zephyrproject/zephyr
        shell: bash
        run: |
          cp ../modules/lib/thrift/scripts/99-thrift.yaml submanifests

      - name: Build and Run Testsuite
        working-directory: zephyrproject/zephyr
        run: |
          source zephyr-env.sh
          twister --retry-failed 3 -i -G -T ../modules/lib/thrift/tests

      - name: Build Samples
        working-directory: zephyrproject/zephyr
        run: |
          source zephyr-env.sh
          twister -i --build-only -G -T ../modules/lib/thrift/samples/
